const DataMeasures = {
  Byte: 1,
  Kilobyte: 1024,
  Megabyte: 1024 ** 2,
  Gigabyte: 1024 ** 3,
  Terabyte: 1024 ** 4,
  Petabyte: 1024 ** 5,
  Exabyte: 1024 ** 6,
  Zettabyte: 1024 ** 7,
  Yottabyte: 1024 ** 8,
};

function convertData(fromUnit, toUnit, value) {
  if (!DataMeasures[fromUnit] || !DataMeasures[toUnit]) {
    throw new Error(`Unsupported data unit: ${fromUnit} or ${toUnit}`);
  }
  return (value * DataMeasures[fromUnit]) / DataMeasures[toUnit];
}

export const data = {
  ByteToKilobyte: (value) => convertData("Byte", "Kilobyte", value),
  ByteToMegabyte: (value) => convertData("Byte", "Megabyte", value),
  ByteToGigabyte: (value) => convertData("Byte", "Gigabyte", value),
  ByteToTerabyte: (value) => convertData("Byte", "Terabyte", value),
  ByteToPetabyte: (value) => convertData("Byte", "Petabyte", value),
  ByteToExabyte: (value) => convertData("Byte", "Exabyte", value),
  ByteToZettabyte: (value) => convertData("Byte", "Zettabyte", value),
  ByteToYottabyte: (value) => convertData("Byte", "Yottabyte", value),
  KilobyteToByte: (value) => convertData("Kilobyte", "Byte", value),
  KilobyteToMegabyte: (value) => convertData("Kilobyte", "Megabyte", value),
  KilobyteToGigabyte: (value) => convertData("Kilobyte", "Gigabyte", value),
  KilobyteToTerabyte: (value) => convertData("Kilobyte", "Terabyte", value),
  KilobyteToPetabyte: (value) => convertData("Kilobyte", "Petabyte", value),
  KilobyteToExabyte: (value) => convertData("Kilobyte", "Exabyte", value),
  KilobyteToZettabyte: (value) => convertData("Kilobyte", "Zettabyte", value),
  KilobyteToYottabyte: (value) => convertData("Kilobyte", "Yottabyte", value),
  MegabyteToByte: (value) => convertData("Megabyte", "Byte", value),
  MegabyteToKilobyte: (value) => convertData("Megabyte", "Kilobyte", value),
  MegabyteToGigabyte: (value) => convertData("Megabyte", "Gigabyte", value),
  MegabyteToTerabyte: (value) => convertData("Megabyte", "Terabyte", value),
  MegabyteToPetabyte: (value) => convertData("Megabyte", "Petabyte", value),
  MegabyteToExabyte: (value) => convertData("Megabyte", "Exabyte", value),
  MegabyteToZettabyte: (value) => convertData("Megabyte", "Zettabyte", value),
  MegabyteToYottabyte: (value) => convertData("Megabyte", "Yottabyte", value),
  GigabyteToByte: (value) => convertData("Gigabyte", "Byte", value),
  GigabyteToKilobyte: (value) => convertData("Gigabyte", "Kilobyte", value),
  GigabyteToMegabyte: (value) => convertData("Gigabyte", "Megabyte", value),
  GigabyteToTerabyte: (value) => convertData("Gigabyte", "Terabyte", value),
  GigabyteToPetabyte: (value) => convertData("Gigabyte", "Petabyte", value),
  GigabyteToExabyte: (value) => convertData("Gigabyte", "Exabyte", value),
  GigabyteToZettabyte: (value) => convertData("Gigabyte", "Zettabyte", value),
  GigabyteToYottabyte: (value) => convertData("Gigabyte", "Yottabyte", value),
  TerabyteToByte: (value) => convertData("Terabyte", "Byte", value),
  TerabyteToKilobyte: (value) => convertData("Terabyte", "Kilobyte", value),
  TerabyteToMegabyte: (value) => convertData("Terabyte", "Megabyte", value),
  TerabyteToGigabyte: (value) => convertData("Terabyte", "Gigabyte", value),
  TerabyteToPetabyte: (value) => convertData("Terabyte", "Petabyte", value),
  TerabyteToExabyte: (value) => convertData("Terabyte", "Exabyte", value),
  TerabyteToZettabyte: (value) => convertData("Terabyte", "Zettabyte", value),
  TerabyteToYottabyte: (value) => convertData("Terabyte", "Yottabyte", value),
  PetabyteToByte: (value) => convertData("Petabyte", "Byte", value),
  PetabyteToKilobyte: (value) => convertData("Petabyte", "Kilobyte", value),
  PetabyteToMegabyte: (value) => convertData("Petabyte", "Megabyte", value),
  PetabyteToGigabyte: (value) => convertData("Petabyte", "Gigabyte", value),
  PetabyteToTerabyte: (value) => convertData("Petabyte", "Terabyte", value),
  PetabyteToExabyte: (value) => convertData("Petabyte", "Exabyte", value),
  PetabyteToZettabyte: (value) => convertData("Petabyte", "Zettabyte", value),
  PetabyteToYottabyte: (value) => convertData("Petabyte", "Yottabyte", value),
  ExabyteToByte: (value) => convertData("Exabyte", "Byte", value),
  ExabyteToKilobyte: (value) => convertData("Exabyte", "Kilobyte", value),
  ExabyteToMegabyte: (value) => convertData("Exabyte", "Megabyte", value),
  ExabyteToGigabyte: (value) => convertData("Exabyte", "Gigabyte", value),
  ExabyteToTerabyte: (value) => convertData("Exabyte", "Terabyte", value),
  ExabyteToPetabyte: (value) => convertData("Exabyte", "Petabyte", value),
  ExabyteToZettabyte: (value) => convertData("Exabyte", "Zettabyte", value),
  ExabyteToYottabyte: (value) => convertData("Exabyte", "Yottabyte", value),
  ZettabyteToByte: (value) => convertData("Zettabyte", "Byte", value),
  ZettabyteToKilobyte: (value) => convertData("Zettabyte", "Kilobyte", value),
  ZettabyteToMegabyte: (value) => convertData("Zettabyte", "Megabyte", value),
  ZettabyteToGigabyte: (value) => convertData("Zettabyte", "Gigabyte", value),
  ZettabyteToTerabyte: (value) => convertData("Zettabyte", "Terabyte", value),
  ZettabyteToPetabyte: (value) => convertData("Zettabyte", "Petabyte", value),
  ZettabyteToExabyte: (value) => convertData("Zettabyte", "Exabyte", value),
  ZettabyteToYottabyte: (value) => convertData("Zettabyte", "Yottabyte", value),
  YottabyteToByte: (value) => convertData("Yottabyte", "Byte", value),
  YottabyteToKilobyte: (value) => convertData("Yottabyte", "Kilobyte", value),
  YottabyteToMegabyte: (value) => convertData("Yottabyte", "Megabyte", value),
  YottabyteToGigabyte: (value) => convertData("Yottabyte", "Gigabyte", value),
  YottabyteToTerabyte: (value) => convertData("Yottabyte", "Terabyte", value),
  YottabyteToPetabyte: (value) => convertData("Yottabyte", "Petabyte", value),
  YottabyteToExabyte: (value) => convertData("Yottabyte", "Exabyte", value),
  YottabyteToZettabyte: (value) => convertData("Yottabyte", "Zettabyte", value),
};
